# Generated by Django 5.2.10 on 2026-01-21 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('tsu_flag', models.BooleanField(default=False)),
                ('eq_flag', models.BooleanField(default=False)),
                ('time_code', models.CharField(blank=True, max_length=20, null=True)),
                ('vei', models.IntegerField(blank=True, null=True)),
                ('agent', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('deaths_description', models.CharField(blank=True, max_length=200, null=True)),
                ('missing', models.IntegerField(blank=True, null=True)),
                ('missing_description', models.CharField(blank=True, max_length=200, null=True)),
                ('injuries', models.IntegerField(blank=True, null=True)),
                ('injuries_description', models.CharField(blank=True, max_length=200, null=True)),
                ('damage_musd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('damage_description', models.CharField(blank=True, max_length=200, null=True)),
                ('houses_destroyed', models.IntegerField(blank=True, null=True)),
                ('houses_destroyed_description', models.CharField(blank=True, max_length=200, null=True)),
                ('total_deaths', models.IntegerField(blank=True, null=True)),
                ('total_deaths_description', models.CharField(blank=True, max_length=200, null=True)),
                ('total_missing', models.IntegerField(blank=True, null=True)),
                ('total_missing_description', models.CharField(blank=True, max_length=200, null=True)),
                ('total_injuries', models.IntegerField(blank=True, null=True)),
                ('total_injuries_description', models.CharField(blank=True, max_length=200, null=True)),
                ('total_damage_musd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_damage_description', models.CharField(blank=True, max_length=200, null=True)),
                ('total_houses_destroyed', models.IntegerField(blank=True, null=True)),
                ('total_houses_destroyed_description', models.CharField(blank=True, max_length=200, null=True)),
                ('eruption', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='volcano.eruption')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='volcano.country')),
            ],
        ),
        migrations.CreateModel(
            name='Volcano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('elevation_m', models.IntegerField(blank=True, null=True)),
                ('volcano_type', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volcanoes', to='volcano.location')),
            ],
        ),
        migrations.AddField(
            model_name='eruption',
            name='volcano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eruptions', to='volcano.volcano'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='uq_location_country_name'),
        ),
        migrations.AddConstraint(
            model_name='volcano',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='uq_volcano_location_name'),
        ),
    ]
